package cl.minsal.semantikos.kernel.domain;

/**
 * Created by root on 08-07-16.
 */
public class Description {
    private long idDescription;
    private long idConcept;
    private long idDescriptionType;
    private String termino;
    private boolean caseSensitive;
    private boolean autogeneratedName;
    private boolean isActive;
    private boolean isPublished;
    private Long idEstadoConcepto;
    private Long usos;

    private DescriptionType descriptionType;

    public long getIdDescripcionConcepto() {
        return idDescription;
    }

    public void setIdDescripcionConcepto(long idDescription) {
        this.idDescription = idDescription;
    }

    public long getIdConcept() {
        return idConcept;
    }

    public void setIdConcept(long idConcept) {
        this.idConcept = idConcept;
    }

    public long getIdDescriptionType() {
        return idDescriptionType;
    }

    public void setIdDescriptionType(long idDescriptionType) {
        this.idDescriptionType = idDescriptionType;
    }

    public String getTermino() {
        return termino;
    }

    public void setTermino(String termino) {
        this.termino = termino;
    }

    public boolean isCaseSensitive() {
        return caseSensitive;
    }

    public void setCaseSensitive(boolean caseSensitive) {
        this.caseSensitive = caseSensitive;
    }

    public boolean isAutogeneratedName() {
        return autogeneratedName;
    }

    public void setAutogeneratedName(boolean autogeneratedName) {
        this.autogeneratedName = autogeneratedName;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    public boolean isPublished() {
        return isPublished;
    }

    public void setPublished(boolean published) {
        isPublished = published;
    }

    public Long getIdEstadoConcepto() {
        return idEstadoConcepto;
    }

    public void setIdEstadoConcepto(Long idEstadoConcepto) {
        this.idEstadoConcepto = idEstadoConcepto;
    }

    public Long getUsos() {
        return usos;
    }

    public void setUsos(Long usos) {
        this.usos = usos;
    }

    public DescriptionType getDescriptionType() {
        return descriptionType;
    }

    public void setDescriptionType(DescriptionType descriptionType) {
        this.descriptionType = descriptionType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Description that = (Description) o;

        if (idDescription != that.idDescription) return false;
        if (idConcept != that.idConcept) return false;
        if (idDescriptionType != that.idDescriptionType) return false;
        if (caseSensitive != that.caseSensitive) return false;
        if (autogeneratedName != that.autogeneratedName) return false;
        if (isActive != that.isActive) return false;
        if (isPublished != that.isPublished) return false;
        if (termino != null ? !termino.equals(that.termino) : that.termino != null) return false;
        if (idEstadoConcepto != null ? !idEstadoConcepto.equals(that.idEstadoConcepto) : that.idEstadoConcepto != null)
            return false;
        if (usos != null ? !usos.equals(that.usos) : that.usos != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = (int) (idDescription ^ (idDescription >>> 32));
        result = 31 * result + (int) (idConcept ^ (idConcept >>> 32));
        result = 31 * result + (int) (idDescriptionType ^ (idDescriptionType >>> 32));
        result = 31 * result + (termino != null ? termino.hashCode() : 0);
        result = 31 * result + (caseSensitive ? 1 : 0);
        result = 31 * result + (autogeneratedName ? 1 : 0);
        result = 31 * result + (isActive ? 1 : 0);
        result = 31 * result + (isPublished ? 1 : 0);
        result = 31 * result + (idEstadoConcepto != null ? idEstadoConcepto.hashCode() : 0);
        result = 31 * result + (usos != null ? usos.hashCode() : 0);
        return result;
    }
}
