package cl.minsal.semantikos.model;

import java.util.Date;

/**
 * Created by root on 08-07-16.
 */
public class Description {

    /** ID en la base de datos */
    private long id;

    /** El término que representa esta descripción */
    private String term;

    /** El DESCRIPTION_ID (valor de negocio) de la descripción */
    private long descriptionID;

    private long idConcept;

    private DescriptionType idDescriptionType;

    private boolean caseSensitive;

    private boolean autogeneratedName;

    private boolean isActive;

    private boolean isPublished;
    private Long idEstadoConcepto;
    private Long usos;

    // El usuario que realizó la última acción sobre el descriptor
    private User user;

    // El instante en que se realizó la última acción sobre el descriptor
    private Date creationDate;

    // El tipo de descriptor
    private DescriptionType descriptionType;

    // El estado del descriptor
    private State state;

    public Description(String theTerm, DescriptionType descriptionType) {

        this.term = theTerm;

        /*
         * Valores por defecto, para efectos de inicialización, existen reglas de negocio para la inicialización por
         * defecto de los campos que deben ser aplicadas separadamente.
         */
        this.autogeneratedName = false;
        this.caseSensitive = false;
        this.isActive = false;
        this.descriptionType = descriptionType;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getDescriptionId() {
        return descriptionID;
    }

    public void setDescriptionId(long idDescription) {
        this.descriptionID = idDescription;
    }

    public long getIdConcept() {
        return idConcept;
    }

    public void setIdConcept(long idConcept) {
        this.idConcept = idConcept;
    }

    public String getTerm() {
        return term;
    }

    public void setTerm(String term) {
        this.term = term;
    }

    public boolean isCaseSensitive() {
        return caseSensitive;
    }

    public void setCaseSensitive(boolean caseSensitive) {
        this.caseSensitive = caseSensitive;
    }

    public boolean isAutogeneratedName() {
        return autogeneratedName;
    }

    public void setAutogeneratedName(boolean autogeneratedName) {
        this.autogeneratedName = autogeneratedName;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    public boolean isPublished() {
        return isPublished;
    }

    public void setPublished(boolean published) {
        isPublished = published;
    }

    public Long getIdEstadoConcepto() {
        return idEstadoConcepto;
    }

    public void setIdEstadoConcepto(Long idEstadoConcepto) {
        this.idEstadoConcepto = idEstadoConcepto;
    }

    public Long getUsos() {
        return usos;
    }

    public void setUsos(Long usos) {
        this.usos = usos;
    }

    public DescriptionType getDescriptionType() {
        return descriptionType;
    }

    public void setDescriptionType(DescriptionType descriptionType) {
        this.descriptionType = descriptionType;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

}
